In [12]:
from pandas_datareader import data
import datetime
from bokeh.plotting import figure,show, output_file
from bokeh.embed import components
start = datetime.datetime(2017,11,25)
end  = datetime.datetime(2018,2,7)
df = data.DataReader(name="GOOG",data_source="yahoo",start=start,end=end)
df

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2017-11-27,1040.000000,1055.459961,1038.439941,1054.209961,1054.209961,1307900
2017-11-28,1055.089966,1062.375000,1040.000000,1047.410034,1047.410034,1424400
2017-11-29,1042.680054,1044.079956,1015.650024,1021.659973,1021.659973,2459400
2017-11-30,1022.369995,1028.489990,1015.000000,1021.409973,1021.409973,1724000
2017-12-01,1015.799988,1022.489990,1002.020020,1010.169983,1010.169983,1909600
2017-12-04,1012.659973,1016.099976,995.570007,998.679993,998.679993,1906400
2017-12-05,995.940002,1020.609985,988.280029,1005.150024,1005.150024,2067300
2017-12-06,1001.500000,1024.969971,1001.140015,1018.380005,1018.380005,1272000
2017-12-07,1020.429993,1034.239990,1018.070984,1030.930054,1030.930054,1458200
2017-12-08,1037.489990,1042.050049,1032.521973,1037.050049,1037.050049,1290800
2017-12-11,1035.500000,1043.800049,1032.050049,1041.099976,1041.099976,1192800
2017-12-12,1039.630005,1050.310059,1033.689941,1040.479980,1040.479980,1279500
2017-12-13,1046.119995,1046.665039,1038.380005,1040.609985,1040.609985,1282700
2017-12-14,1045.000000,1058.500000,1043.109985,1049.150024,1049.150024,1558700
2017-12-15,1054.609985,1067.619995,1049.500000,1064.189941,1064.189941,3275900
2017-12-18,1066.079956,1078.489990,1062.000000,1077.140015,1077.140015,1554600
2017-12-19,1075.199951,1076.839966,1063.550049,1070.680054,1070.680054,1338700
2017-12-20,1071.780029,1073.380005,1061.520020,1064.949951,1064.949951,1268600
2017-12-21,1064.949951,1069.329956,1061.793945,1063.630005,1063.630005,995700
2017-12-22,1061.109985,1064.199951,1059.439941,1060.119995,1060.119995,755100
2017-12-26,1058.069946,1060.119995,1050.199951,1056.739990,1056.739990,760600
2017-12-27,1057.390015,1058.369995,1048.050049,1049.369995,1049.369995,1271900
2017-12-28,1051.599976,1054.750000,1044.770020,1048.140015,1048.140015,837100
2017-12-29,1046.719971,1049.699951,1044.900024,1046.400024,1046.400024,887500
2018-01-02,1048.339966,1066.939941,1045.229980,1065.000000,1065.000000,1237600
2018-01-03,1064.310059,1086.290039,1063.209961,1082.479980,1082.479980,1430200
2018-01-04,1088.000000,1093.569946,1084.001953,1086.400024,1086.400024,1004600
2018-01-05,1094.000000,1104.250000,1092.000000,1102.229980,1102.229980,1279100
2018-01-08,1102.229980,1111.270020,1101.619995,1106.939941,1106.939941,1047600
2018-01-09,1109.400024,1110.569946,1101.230957,1106.260010,1106.260010,902500
2018-01-10,1097.099976,1104.599976,1096.109985,1102.609985,1102.609985,1042800
2018-01-11,1106.300049,1106.525024,1099.589966,1105.520020,1105.520020,978300
2018-01-12,1102.410034,1124.290039,1101.150024,1122.260010,1122.260010,1720500
2018-01-16,1132.510010,1139.910034,1117.832031,1121.760010,1121.760010,1575300
2018-01-17,1126.219971,1132.599976,1117.010010,1131.979980,1131.979980,1202600
2018-01-18,1131.410034,1132.510010,1117.500000,1129.790039,1129.790039,1198200
2018-01-19,1131.829956,1137.859985,1128.300049,1137.510010,1137.510010,1778200
2018-01-22,1137.489990,1159.880005,1135.109985,1155.810059,1155.810059,1618000
2018-01-23,1159.849976,1171.626953,1158.750000,1169.969971,1169.969971,1333100
2018-01-24,1177.329956,1179.859985,1161.050049,1164.239990,1164.239990,1416600
2018-01-25,1172.530029,1175.939941,1162.760010,1170.369995,1170.369995,1480500
2018-01-26,1175.079956,1175.839966,1158.109985,1175.839966,1175.839966,2018800
2018-01-29,1176.479980,1186.890015,1171.979980,1175.579956,1175.579956,1378900
2018-01-30,1167.829956,1176.520020,1163.520020,1163.689941,1163.689941,1556300
2018-01-31,1170.569946,1173.000000,1159.130005,1169.939941,1169.939941,1538700
2018-02-01,1162.609985,1174.000000,1157.520020,1167.699951,1167.699951,2412100
2018-02-02,1122.000000,1123.069946,1107.277954,1111.900024,1111.900024,4857900
2018-02-05,1090.599976,1110.000000,1052.030029,1055.800049,1055.800049,3798300
2018-02-06,1027.180054,1081.709961,1023.137024,1080.599976,1080.599976,3448000
2018-02-07,1081.540039,1081.780029,1048.260010,1048.579956,1048.579956,2369200

In [4]:
df.Close

Date
2017-12-26    1056.739990
2017-12-27    1049.369995
2017-12-28    1048.140015
2017-12-29    1046.400024
2018-01-02    1065.000000
2018-01-03    1082.479980
2018-01-04    1086.400024
2018-01-05    1102.229980
Name: Close, dtype: float64

In [10]:
 def inc_dec(c, o):
        if c > o:
            value="Increase"
        elif c < o:
            value="Decrease"
        else:
            value="Equal"
        return value
df["Status"]=[inc_dec(c,o) for c, o in zip(df.Close,df.Open)]
df["Middle"]=(df.Open+df.Close)/2
df["Height"]=abs(df.Close-df.Open)

p=figure(x_axis_type='datetime', width=1000, height=300, sizing_mode="scale_both")
p.title.text="Candlestick Chart"
p.grid.grid_line_alpha=0.3

hours_12=12*60*60*1000

p.segment(df.index, df.High, df.index, df.Low, color="Black")

p.rect(df.index[df.Status=="Increase"],df.Middle[df.Status=="Increase"],
       hours_12, df.Height[df.Status=="Increase"],fill_color="#7FFF00",line_color="black")

p.rect(df.index[df.Status=="Decrease"],df.Middle[df.Status=="Decrease"],
       hours_12, df.Height[df.Status=="Decrease"],fill_color="#F08080",line_color="black")

show(p)

In [17]:
from bokeh.resources import CDN
script1,div1 = components(p)
# print(script1)
# print(div1)
cdn_js=CDN.js_files
cdn_css=CDN.css_files

In [18]:
cdn_js

['https://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.js',
 'https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.13.min.js',
 'https://cdn.pydata.org/bokeh/release/bokeh-tables-0.12.13.min.js',
 'https://cdn.pydata.org/bokeh/release/bokeh-gl-0.12.13.min.js']